name: Tests

on:
  push:
    branches: '*'
    
  pull_request:
    branches: '*'
    
  workflow_dispatch:

jobs:
  run-tests:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/cache@v3
      id: cache-deps
      with:
        path: external
        key: ${{ runner.os }}-deps-${{ hashFiles('/home/runner/work/Cascade/Cascade/scripts/install_deps.sh') }}

    - name: Build dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: | 
        cd scripts
        sh install-deps.sh 
        cd ..
    
    - name: Install packages
      run: | 
        sudo apt update
        sudo apt install -y libopenimageio-dev libgtest-dev google-mock libtbb-dev build-essential qtbase5-dev qt5-qmake qtbase5-dev-tools libopenexr-dev cmake libglew-dev freeglut3-dev

    - name: Build test project
      run: | 
        cd test/CascadeTests
        qmake
        make -j4
        
    - name: Run Tests
      run: |
        ./test/CascadeTests/CascadeTests -platform offscreen
